const key='nutriday-v1';
const defaults={goals:{calories:2000,protein:100,carbs:250,fat:70,fiber:28,water:8},water:5,meals:[{name:'Greek yogurt with berries',meal:'Breakfast',calories:280,protein:20,carbs:34,fat:6,fiber:5,emoji:'🥣'},{name:'Avocado toast',meal:'Breakfast',calories:320,protein:12,carbs:38,fat:14,fiber:8,emoji:'🥑'},{name:'Grilled chicken salad',meal:'Lunch',calories:480,protein:38,carbs:32,fat:21,fiber:7,emoji:'🥗'},{name:'Apple',meal:'Snack',calories:104,protein:1,carbs:28,fat:0,fiber:5,emoji:'🍎'}]};
let state;try{state={...defaults,...JSON.parse(localStorage.getItem(key)||'{}')};state.goals={...defaults.goals,...(state.goals||{})};state.meals=Array.isArray(state.meals)?state.meals:defaults.meals}catch{state=structuredClone(defaults)}
let selectedDate=new Date();let toastTimer;
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const icons=['◌','✳','⌁','◍'];const macroDefs=[['Protein','protein','g'],['Carbs','carbs','g'],['Fat','fat','g'],['Fiber','fiber','g']];
function save(){localStorage.setItem(key,JSON.stringify(state))}
function sums(){return state.meals.reduce((a,m)=>{for(const k of ['calories','protein','carbs','fat','fiber'])a[k]=(a[k]||0)+(Number(m[k])||0);return a},{})}
function fmt(n){return Math.round(n||0).toLocaleString()}
function render(){const s=sums(),g=state.goals,cal=s.calories||0,pct=Math.min(100,cal/g.calories*100);$('#caloriesValue').textContent=fmt(cal);$('#caloriesEatenLabel').textContent=fmt(cal);$('#caloriesGoalLabel').textContent=fmt(g.calories);$('#caloriesLeft').innerHTML=`${fmt(Math.max(0,g.calories-cal))} <small>kcal</small>`;$('#caloriePercent').textContent=`${Math.round(pct)}% of goal`;$('#calorieRing').style.strokeDashoffset=477.5*(1-pct/100);$('#waterValue').textContent=state.water;$('#waterGlasses').innerHTML=Array.from({length:Math.min(g.water,20)},(_,i)=>`<span class="glass ${i<state.water?'full':''}" aria-label="Glass ${i+1}${i<state.water?' full':''}"></span>`).join('');
  $('#macroGrid').innerHTML=macroDefs.map(([name,key,unit],i)=>{let val=s[key]||0,goal=g[key]||0,percent=goal?Math.min(100,val/goal*100):0;return `<article class="macro-card"><div class="macro-top"><span class="macro-icon">${icons[i]}</span><span class="eyebrow">${Math.round(percent)}%</span></div><div class="macro-name">${name}</div><div class="macro-val">${fmt(val)} <small>${unit}</small></div><div class="macro-target">of ${fmt(goal)} ${unit} goal</div><div class="bar-track"><div class="bar-fill" style="width:${percent}%"></div></div></article>`}).join('');
  $('#mealList').innerHTML=state.meals.length?state.meals.map((m,i)=>`<div class="meal-row"><span class="meal-emoji">${m.emoji||'🍽️'}</span><div><div class="meal-name">${escapeHtml(m.name)}</div><div class="meal-meta">${escapeHtml(m.meal)} · ${fmt(m.protein)}g protein</div></div><span class="meal-cal">${fmt(m.calories)} <small>kcal</small></span></div>`).join(''):'<div class="empty-meals">Nothing logged yet. Add your first bite to get started.</div>';
  $('#insightCards').innerHTML=`<article class="card insight-stat"><div class="eyebrow">ENERGY TODAY</div><strong>${fmt(cal)} <small>kcal</small></strong><p>${Math.round(pct)}% of your daily energy goal</p></article><article class="card insight-stat"><div class="eyebrow">PROTEIN</div><strong>${fmt(s.protein)} <small>g</small></strong><p>${Math.max(0,fmt(g.protein-(s.protein||0)))}g to your daily goal</p></article><article class="card insight-stat"><div class="eyebrow">WATER</div><strong>${state.water} <small>glasses</small></strong><p>${Math.max(0,g.water-state.water)} more to reach your goal</p></article>`;
  $('#insightBars').innerHTML=[['Calories',cal,g.calories,'kcal'],...macroDefs.map(([n,k])=>[n,s[k]||0,g[k]||0,'g'])].map(([n,v,goal,u])=>`<div class="insight-line"><span>${n}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,v/goal*100)}%"></div></div><b>${fmt(v)} / ${fmt(goal)} ${u}</b></div>`).join('');
  $('#goalCalories').value=g.calories;$('#goalProtein').value=g.protein;$('#goalCarbs').value=g.carbs;$('#goalFat').value=g.fat;$('#goalWater').value=g.water;
}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2200)}
function updateDate(){let same=selectedDate.toDateString()===new Date().toDateString();$('#dateLabel').textContent=same?`Today, ${selectedDate.toLocaleDateString('en-US',{month:'long',day:'numeric'})}`:selectedDate.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});$('.welcome-row .eyebrow').textContent=selectedDate.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}).toUpperCase()}
function go(page){$$('.page').forEach(x=>x.classList.remove('active'));$(`#${page}Page`).classList.add('active');$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$('#profileShortcut').addEventListener('click',()=>go('profile'));
$('#prevDay').addEventListener('click',()=>{selectedDate.setDate(selectedDate.getDate()-1);updateDate();showToast('Showing your daily view')});$('#nextDay').addEventListener('click',()=>{selectedDate.setDate(selectedDate.getDate()+1);updateDate();showToast('Showing your daily view')});
$('#addWater').addEventListener('click',()=>{if(state.water>=state.goals.water){showToast('You reached your water goal for today!');return}state.water++;save();render();showToast('Water logged — nice work!')});
const dialog=$('#foodDialog');$('#addFoodTop').addEventListener('click',()=>dialog.showModal());$('#addFoodMeal').addEventListener('click',()=>dialog.showModal());$('#foodForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const f=new FormData(e.currentTarget);const meal=f.get('meal');const emoji={Breakfast:'🍳',Lunch:'🥗',Dinner:'🍲',Snack:'🍎'}[meal]||'🍽️';state.meals.push({name:f.get('name').trim(),meal,calories:+f.get('calories'),protein:+f.get('protein')||0,carbs:+f.get('carbs')||0,fat:+f.get('fat')||0,fiber:+f.get('fiber')||0,emoji});save();render();e.currentTarget.reset();dialog.close();showToast('Added to your food journal')});
$('#saveGoals').addEventListener('click',()=>{for(const k of ['calories','protein','carbs','fat','water']){const n=Number($(`#goal${k[0].toUpperCase()+k.slice(1)}`).value);if(n>0)state.goals[k]=n}save();render();showToast('Your goals have been updated')});
updateDate();render();

